"""Pure contract specification seed data (no DB access)."""

CONTRACT_SPEC_SEED: list[dict] = [
    # ---- FOREX (Deriv FRX prefix) ----
    {"symbol": "FRXEURUSD", "asset_class": "forex",
     "pip_size": 0.00001, "point_value": 10.0,
     "contract_size": 100000.0,
     "lot_size_min": 0.01, "lot_size_max": 100.0,
     "lot_size_step": 0.01,
     "quote_currency": "USD", "base_currency": "EUR",
     "is_crypto": False, "notes": "USD quoted direct"},
    {"symbol": "FRXGBPUSD", "asset_class": "forex",
     "pip_size": 0.00001, "point_value": 10.0,
     "contract_size": 100000.0,
     "lot_size_min": 0.01, "lot_size_max": 100.0,
     "lot_size_step": 0.01,
     "quote_currency": "USD", "base_currency": "GBP",
     "is_crypto": False, "notes": "USD quoted direct"},
    {"symbol": "FRXAUDUSD", "asset_class": "forex",
     "pip_size": 0.00001, "point_value": 10.0,
     "contract_size": 100000.0,
     "lot_size_min": 0.01, "lot_size_max": 100.0,
     "lot_size_step": 0.01,
     "quote_currency": "USD", "base_currency": "AUD",
     "is_crypto": False, "notes": "USD quoted direct"},
    {"symbol": "FRXNZDUSD", "asset_class": "forex",
     "pip_size": 0.00001, "point_value": 10.0,
     "contract_size": 100000.0,
     "lot_size_min": 0.01, "lot_size_max": 100.0,
     "lot_size_step": 0.01,
     "quote_currency": "USD", "base_currency": "NZD",
     "is_crypto": False, "notes": "USD quoted direct"},
    {"symbol": "FRXUSDJPY", "asset_class": "forex",
     "pip_size": 0.001, "point_value": 0.0,
     "contract_size": 100000.0,
     "lot_size_min": 0.01, "lot_size_max": 100.0,
     "lot_size_step": 0.01,
     "quote_currency": "JPY", "base_currency": "USD",
     "is_crypto": False,
     "notes": "point_value=0 means compute live: pip*contract/rate"},
    {"symbol": "FRXUSDCHF", "asset_class": "forex",
     "pip_size": 0.00001, "point_value": 0.0,
     "contract_size": 100000.0,
     "lot_size_min": 0.01, "lot_size_max": 100.0,
     "lot_size_step": 0.01,
     "quote_currency": "CHF", "base_currency": "USD",
     "is_crypto": False, "notes": "compute live"},
    {"symbol": "FRXUSDCAD", "asset_class": "forex",
     "pip_size": 0.00001, "point_value": 0.0,
     "contract_size": 100000.0,
     "lot_size_min": 0.01, "lot_size_max": 100.0,
     "lot_size_step": 0.01,
     "quote_currency": "CAD", "base_currency": "USD",
     "is_crypto": False, "notes": "compute live"},
    {"symbol": "FRXEURGBP", "asset_class": "forex",
     "pip_size": 0.00001, "point_value": 0.0,
     "contract_size": 100000.0,
     "lot_size_min": 0.01, "lot_size_max": 100.0,
     "lot_size_step": 0.01,
     "quote_currency": "GBP", "base_currency": "EUR",
     "is_crypto": False, "notes": "cross pair compute live via GBPUSD"},
    {"symbol": "FRXEURJPY", "asset_class": "forex",
     "pip_size": 0.001, "point_value": 0.0,
     "contract_size": 100000.0,
     "lot_size_min": 0.01, "lot_size_max": 100.0,
     "lot_size_step": 0.01,
     "quote_currency": "JPY", "base_currency": "EUR",
     "is_crypto": False, "notes": "cross pair compute live via USDJPY"},
    {"symbol": "FRXEURCHF", "asset_class": "forex",
     "pip_size": 0.00001, "point_value": 0.0,
     "contract_size": 100000.0,
     "lot_size_min": 0.01, "lot_size_max": 100.0,
     "lot_size_step": 0.01,
     "quote_currency": "CHF", "base_currency": "EUR",
     "is_crypto": False, "notes": "cross pair compute live"},
    {"symbol": "FRXEURAUD", "asset_class": "forex",
     "pip_size": 0.00001, "point_value": 0.0,
     "contract_size": 100000.0,
     "lot_size_min": 0.01, "lot_size_max": 100.0,
     "lot_size_step": 0.01,
     "quote_currency": "AUD", "base_currency": "EUR",
     "is_crypto": False, "notes": "cross pair compute live via AUDUSD"},
    {"symbol": "FRXEURCAD", "asset_class": "forex",
     "pip_size": 0.00001, "point_value": 0.0,
     "contract_size": 100000.0,
     "lot_size_min": 0.01, "lot_size_max": 100.0,
     "lot_size_step": 0.01,
     "quote_currency": "CAD", "base_currency": "EUR",
     "is_crypto": False, "notes": "cross pair compute live via USDCAD"},
    {"symbol": "FRXEURNZD", "asset_class": "forex",
     "pip_size": 0.00001, "point_value": 0.0,
     "contract_size": 100000.0,
     "lot_size_min": 0.01, "lot_size_max": 100.0,
     "lot_size_step": 0.01,
     "quote_currency": "NZD", "base_currency": "EUR",
     "is_crypto": False, "notes": "cross pair compute live via NZDUSD"},
    {"symbol": "FRXGBPJPY", "asset_class": "forex",
     "pip_size": 0.001, "point_value": 0.0,
     "contract_size": 100000.0,
     "lot_size_min": 0.01, "lot_size_max": 100.0,
     "lot_size_step": 0.01,
     "quote_currency": "JPY", "base_currency": "GBP",
     "is_crypto": False, "notes": "cross pair compute live via USDJPY"},
    {"symbol": "FRXGBPCHF", "asset_class": "forex",
     "pip_size": 0.00001, "point_value": 0.0,
     "contract_size": 100000.0,
     "lot_size_min": 0.01, "lot_size_max": 100.0,
     "lot_size_step": 0.01,
     "quote_currency": "CHF", "base_currency": "GBP",
     "is_crypto": False, "notes": "cross pair compute live"},
    {"symbol": "FRXGBPAUD", "asset_class": "forex",
     "pip_size": 0.00001, "point_value": 0.0,
     "contract_size": 100000.0,
     "lot_size_min": 0.01, "lot_size_max": 100.0,
     "lot_size_step": 0.01,
     "quote_currency": "AUD", "base_currency": "GBP",
     "is_crypto": False, "notes": "cross pair compute live via AUDUSD"},
    {"symbol": "FRXGBPCAD", "asset_class": "forex",
     "pip_size": 0.00001, "point_value": 0.0,
     "contract_size": 100000.0,
     "lot_size_min": 0.01, "lot_size_max": 100.0,
     "lot_size_step": 0.01,
     "quote_currency": "CAD", "base_currency": "GBP",
     "is_crypto": False, "notes": "cross pair compute live via USDCAD"},
    {"symbol": "FRXGBPNZD", "asset_class": "forex",
     "pip_size": 0.00001, "point_value": 0.0,
     "contract_size": 100000.0,
     "lot_size_min": 0.01, "lot_size_max": 100.0,
     "lot_size_step": 0.01,
     "quote_currency": "NZD", "base_currency": "GBP",
     "is_crypto": False, "notes": "cross pair compute live via NZDUSD"},
    {"symbol": "FRXAUDJPY", "asset_class": "forex",
     "pip_size": 0.001, "point_value": 0.0,
     "contract_size": 100000.0,
     "lot_size_min": 0.01, "lot_size_max": 100.0,
     "lot_size_step": 0.01,
     "quote_currency": "JPY", "base_currency": "AUD",
     "is_crypto": False, "notes": "cross pair compute live via USDJPY"},
    {"symbol": "FRXAUDNZD", "asset_class": "forex",
     "pip_size": 0.00001, "point_value": 0.0,
     "contract_size": 100000.0,
     "lot_size_min": 0.01, "lot_size_max": 100.0,
     "lot_size_step": 0.01,
     "quote_currency": "NZD", "base_currency": "AUD",
     "is_crypto": False, "notes": "cross pair compute live via NZDUSD"},
    {"symbol": "FRXAUDCAD", "asset_class": "forex",
     "pip_size": 0.00001, "point_value": 0.0,
     "contract_size": 100000.0,
     "lot_size_min": 0.01, "lot_size_max": 100.0,
     "lot_size_step": 0.01,
     "quote_currency": "CAD", "base_currency": "AUD",
     "is_crypto": False, "notes": "cross pair compute live via USDCAD"},
    {"symbol": "FRXCADJPY", "asset_class": "forex",
     "pip_size": 0.001, "point_value": 0.0,
     "contract_size": 100000.0,
     "lot_size_min": 0.01, "lot_size_max": 100.0,
     "lot_size_step": 0.01,
     "quote_currency": "JPY", "base_currency": "CAD",
     "is_crypto": False, "notes": "cross pair compute live via USDJPY"},
    {"symbol": "FRXCHFJPY", "asset_class": "forex",
     "pip_size": 0.001, "point_value": 0.0,
     "contract_size": 100000.0,
     "lot_size_min": 0.01, "lot_size_max": 100.0,
     "lot_size_step": 0.01,
     "quote_currency": "JPY", "base_currency": "CHF",
     "is_crypto": False, "notes": "cross pair compute live via USDJPY"},
    {"symbol": "FRXNZDJPY", "asset_class": "forex",
     "pip_size": 0.001, "point_value": 0.0,
     "contract_size": 100000.0,
     "lot_size_min": 0.01, "lot_size_max": 100.0,
     "lot_size_step": 0.01,
     "quote_currency": "JPY", "base_currency": "NZD",
     "is_crypto": False, "notes": "cross pair compute live via USDJPY"},
    {"symbol": "FRXUSDSGD", "asset_class": "forex",
     "pip_size": 0.00001, "point_value": 0.0,
     "contract_size": 100000.0,
     "lot_size_min": 0.01, "lot_size_max": 100.0,
     "lot_size_step": 0.01,
     "quote_currency": "SGD", "base_currency": "USD",
     "is_crypto": False, "notes": "compute live"},
    {"symbol": "FRXUSDHKD", "asset_class": "forex",
     "pip_size": 0.00001, "point_value": 0.0,
     "contract_size": 100000.0,
     "lot_size_min": 0.01, "lot_size_max": 100.0,
     "lot_size_step": 0.01,
     "quote_currency": "HKD", "base_currency": "USD",
     "is_crypto": False, "notes": "compute live"},
    {"symbol": "FRXUSDMXN", "asset_class": "forex",
     "pip_size": 0.0001, "point_value": 0.0,
     "contract_size": 100000.0,
     "lot_size_min": 0.01, "lot_size_max": 100.0,
     "lot_size_step": 0.01,
     "quote_currency": "MXN", "base_currency": "USD",
     "is_crypto": False, "notes": "compute live"},
    {"symbol": "FRXUSDSEK", "asset_class": "forex",
     "pip_size": 0.00001, "point_value": 0.0,
     "contract_size": 100000.0,
     "lot_size_min": 0.01, "lot_size_max": 100.0,
     "lot_size_step": 0.01,
     "quote_currency": "SEK", "base_currency": "USD",
     "is_crypto": False, "notes": "compute live"},
    {"symbol": "FRXUSDNOK", "asset_class": "forex",
     "pip_size": 0.00001, "point_value": 0.0,
     "contract_size": 100000.0,
     "lot_size_min": 0.01, "lot_size_max": 100.0,
     "lot_size_step": 0.01,
     "quote_currency": "NOK", "base_currency": "USD",
     "is_crypto": False, "notes": "compute live"},
    {"symbol": "FRXUSDDKK", "asset_class": "forex",
     "pip_size": 0.00001, "point_value": 0.0,
     "contract_size": 100000.0,
     "lot_size_min": 0.01, "lot_size_max": 100.0,
     "lot_size_step": 0.01,
     "quote_currency": "DKK", "base_currency": "USD",
     "is_crypto": False, "notes": "compute live"},
    {"symbol": "FRXEURSEK", "asset_class": "forex",
     "pip_size": 0.00001, "point_value": 0.0,
     "contract_size": 100000.0,
     "lot_size_min": 0.01, "lot_size_max": 100.0,
     "lot_size_step": 0.01,
     "quote_currency": "SEK", "base_currency": "EUR",
     "is_crypto": False, "notes": "cross pair compute live"},
    {"symbol": "FRXEURNOK", "asset_class": "forex",
     "pip_size": 0.00001, "point_value": 0.0,
     "contract_size": 100000.0,
     "lot_size_min": 0.01, "lot_size_max": 100.0,
     "lot_size_step": 0.01,
     "quote_currency": "NOK", "base_currency": "EUR",
     "is_crypto": False, "notes": "cross pair compute live"},
    {"symbol": "FRXGBPNOK", "asset_class": "forex",
     "pip_size": 0.00001, "point_value": 0.0,
     "contract_size": 100000.0,
     "lot_size_min": 0.01, "lot_size_max": 100.0,
     "lot_size_step": 0.01,
     "quote_currency": "NOK", "base_currency": "GBP",
     "is_crypto": False, "notes": "cross pair compute live"},
    # ---- COMMODITIES ----
    {"symbol": "FRXXAUUSD", "asset_class": "commodity",
     "pip_size": 0.01, "point_value": 100.0,
     "contract_size": 100.0,
     "lot_size_min": 0.01, "lot_size_max": 100.0,
     "lot_size_step": 0.01,
     "quote_currency": "USD", "base_currency": "XAU",
     "is_crypto": False,
     "notes": "$1 move = $100/lot. point_value=100"},
    {"symbol": "XAUUSD", "asset_class": "commodity",
     "pip_size": 0.01, "point_value": 100.0,
     "contract_size": 100.0,
     "lot_size_min": 0.01, "lot_size_max": 100.0,
     "lot_size_step": 0.01,
     "quote_currency": "USD", "base_currency": "XAU",
     "is_crypto": False, "notes": "same as FRXXAUUSD"},
    {"symbol": "FRXXAGUSD", "asset_class": "commodity",
     "pip_size": 0.001, "point_value": 50.0,
     "contract_size": 5000.0,
     "lot_size_min": 0.01, "lot_size_max": 100.0,
     "lot_size_step": 0.01,
     "quote_currency": "USD", "base_currency": "XAG",
     "is_crypto": False,
     "notes": "Deriv pip=0.0001 from active_symbols. verify"},
    {"symbol": "USOIL", "asset_class": "commodity",
     "pip_size": 0.01, "point_value": 100.0,
     "contract_size": 100.0,
     "lot_size_min": 0.01, "lot_size_max": 100.0,
     "lot_size_step": 0.01,
     "quote_currency": "USD", "base_currency": "OIL",
     "is_crypto": False,
     "notes": "Deriv retail CFD 100 barrels/lot"},
    {"symbol": "FRXXPTUSD", "asset_class": "commodity",
     "pip_size": 0.01, "point_value": 100.0,
     "contract_size": 100.0,
     "lot_size_min": 0.01, "lot_size_max": 100.0,
     "lot_size_step": 0.01,
     "quote_currency": "USD", "base_currency": "XPT",
     "is_crypto": False, "notes": "Deriv active_symbols pip=0.01"},
    # ---- SYNTHETICS (pip from Deriv active_symbols) ----
    {"symbol": "R_10", "asset_class": "synthetic",
     "pip_size": 0.001, "point_value": 0.001,
     "contract_size": 1.0,
     "lot_size_min": 0.01, "lot_size_max": 100.0,
     "lot_size_step": 0.01,
     "quote_currency": None, "base_currency": None,
     "is_crypto": False,
     "notes": "Deriv active_symbols pip=0.001"},
    {"symbol": "R_50", "asset_class": "synthetic",
     "pip_size": 0.0001, "point_value": 0.0001,
     "contract_size": 1.0,
     "lot_size_min": 0.01, "lot_size_max": 100.0,
     "lot_size_step": 0.01,
     "quote_currency": None, "base_currency": None,
     "is_crypto": False,
     "notes": "Deriv active_symbols pip=0.0001"},
    {"symbol": "R_75", "asset_class": "synthetic",
     "pip_size": 0.0001, "point_value": 0.0001,
     "contract_size": 1.0,
     "lot_size_min": 0.001, "lot_size_max": 100.0,
     "lot_size_step": 0.001,
     "quote_currency": None, "base_currency": None,
     "is_crypto": False,
     "notes": "Deriv active_symbols pip=0.0001"},
    {"symbol": "1HZ15V", "asset_class": "synthetic",
     "pip_size": 0.001, "point_value": 0.001,
     "contract_size": 1.0,
     "lot_size_min": 0.001, "lot_size_max": 100.0,
     "lot_size_step": 0.001,
     "quote_currency": None, "base_currency": None,
     "is_crypto": False,
     "notes": "Deriv active_symbols pip=0.001"},
    {"symbol": "1HZ50V", "asset_class": "synthetic",
     "pip_size": 0.01, "point_value": 0.01,
     "contract_size": 1.0,
     "lot_size_min": 0.001, "lot_size_max": 100.0,
     "lot_size_step": 0.001,
     "quote_currency": None, "base_currency": None,
     "is_crypto": False,
     "notes": "Deriv active_symbols pip=0.01"},
    {"symbol": "1HZ75V", "asset_class": "synthetic",
     "pip_size": 0.01, "point_value": 0.01,
     "contract_size": 1.0,
     "lot_size_min": 0.001, "lot_size_max": 100.0,
     "lot_size_step": 0.001,
     "quote_currency": None, "base_currency": None,
     "is_crypto": False,
     "notes": "Deriv active_symbols pip=0.01"},
    {"symbol": "1HZ90V", "asset_class": "synthetic",
     "pip_size": 0.001, "point_value": 0.001,
     "contract_size": 1.0,
     "lot_size_min": 0.001, "lot_size_max": 100.0,
     "lot_size_step": 0.001,
     "quote_currency": None, "base_currency": None,
     "is_crypto": False,
     "notes": "Deriv active_symbols pip=0.001"},
    {"symbol": "BOOM1000", "asset_class": "synthetic",
     "pip_size": 0.001, "point_value": 0.001,
     "contract_size": 1.0,
     "lot_size_min": 0.20, "lot_size_max": 100.0,
     "lot_size_step": 0.01,
     "quote_currency": None, "base_currency": None,
     "is_crypto": False,
     "notes": "Deriv pip=0.001. lot_min=0.20 Gemini-verified"},
    {"symbol": "BOOM300N", "asset_class": "synthetic",
     "pip_size": 0.001, "point_value": 0.001,
     "contract_size": 1.0,
     "lot_size_min": 1.0, "lot_size_max": 100.0,
     "lot_size_step": 1.0,
     "quote_currency": None, "base_currency": None,
     "is_crypto": False,
     "notes": "Deriv pip=0.001. lot_min=1.0 Gemini-verified"},
    {"symbol": "BOOM150N", "asset_class": "synthetic",
     "pip_size": 0.00001, "point_value": 0.00001,
     "contract_size": 1.0,
     "lot_size_min": 1.0, "lot_size_max": 100.0,
     "lot_size_step": 1.0,
     "quote_currency": None, "base_currency": None,
     "is_crypto": False,
     "notes": "Deriv pip=1e-05"},
    {"symbol": "BOOM50", "asset_class": "synthetic",
     "pip_size": 0.001, "point_value": 0.001,
     "contract_size": 1.0,
     "lot_size_min": 0.20, "lot_size_max": 100.0,
     "lot_size_step": 0.01,
     "quote_currency": None, "base_currency": None,
     "is_crypto": False, "notes": "Deriv pip=0.001"},
    {"symbol": "CRASH1000", "asset_class": "synthetic",
     "pip_size": 0.001, "point_value": 0.001,
     "contract_size": 1.0,
     "lot_size_min": 0.20, "lot_size_max": 100.0,
     "lot_size_step": 0.01,
     "quote_currency": None, "base_currency": None,
     "is_crypto": False,
     "notes": "Deriv pip=0.001. lot_min=0.20 Gemini-verified"},
    {"symbol": "CRASH600", "asset_class": "synthetic",
     "pip_size": 0.001, "point_value": 0.001,
     "contract_size": 1.0,
     "lot_size_min": 0.20, "lot_size_max": 100.0,
     "lot_size_step": 0.01,
     "quote_currency": None, "base_currency": None,
     "is_crypto": False, "notes": "Deriv pip=0.001"},
    {"symbol": "CRASH900", "asset_class": "synthetic",
     "pip_size": 0.001, "point_value": 0.001,
     "contract_size": 1.0,
     "lot_size_min": 0.20, "lot_size_max": 100.0,
     "lot_size_step": 0.01,
     "quote_currency": None, "base_currency": None,
     "is_crypto": False, "notes": "Deriv pip=0.001"},
    {"symbol": "JD10", "asset_class": "synthetic",
     "pip_size": 0.01, "point_value": 0.01,
     "contract_size": 1.0,
     "lot_size_min": 0.01, "lot_size_max": 100.0,
     "lot_size_step": 0.01,
     "quote_currency": None, "base_currency": None,
     "is_crypto": False,
     "notes": "Deriv pip=0.01. lot_min=0.01 Gemini-verified"},
    {"symbol": "JD50", "asset_class": "synthetic",
     "pip_size": 0.01, "point_value": 0.01,
     "contract_size": 1.0,
     "lot_size_min": 0.01, "lot_size_max": 100.0,
     "lot_size_step": 0.01,
     "quote_currency": None, "base_currency": None,
     "is_crypto": False, "notes": "Deriv pip=0.01"},
    {"symbol": "JD100", "asset_class": "synthetic",
     "pip_size": 0.01, "point_value": 0.01,
     "contract_size": 1.0,
     "lot_size_min": 0.01, "lot_size_max": 100.0,
     "lot_size_step": 0.01,
     "quote_currency": None, "base_currency": None,
     "is_crypto": False, "notes": "Deriv pip=0.01"},
    {"symbol": "WLDAUD", "asset_class": "synthetic",
     "pip_size": 0.001, "point_value": 0.001,
     "contract_size": 1.0,
     "lot_size_min": 1.0, "lot_size_max": 100.0,
     "lot_size_step": 1.0,
     "quote_currency": None, "base_currency": None,
     "is_crypto": False,
     "notes": "Deriv pip=0.001. lot_min=1.0 Gemini DEX"},
    {"symbol": "RDBULL", "asset_class": "synthetic",
     "pip_size": 0.0001, "point_value": 0.0001,
     "contract_size": 1.0,
     "lot_size_min": 0.01, "lot_size_max": 100.0,
     "lot_size_step": 0.01,
     "quote_currency": None, "base_currency": None,
     "is_crypto": False, "notes": "Deriv pip=0.0001"},
    {"symbol": "RB100", "asset_class": "synthetic",
     "pip_size": 0.1, "point_value": 0.1,
     "contract_size": 1.0,
     "lot_size_min": 0.1, "lot_size_max": 100.0,
     "lot_size_step": 0.1,
     "quote_currency": None, "base_currency": None,
     "is_crypto": False,
     "notes": "Deriv pip=0.1. Step Index family"},
    {"symbol": "OTC_DJI", "asset_class": "synthetic",
     "pip_size": 0.01, "point_value": 0.01,
     "contract_size": 1.0,
     "lot_size_min": 0.01, "lot_size_max": 100.0,
     "lot_size_step": 0.01,
     "quote_currency": None, "base_currency": None,
     "is_crypto": False, "notes": "Deriv OTC pip=0.01"},
    {"symbol": "OTC_NDX", "asset_class": "synthetic",
     "pip_size": 0.01, "point_value": 0.01,
     "contract_size": 1.0,
     "lot_size_min": 0.01, "lot_size_max": 100.0,
     "lot_size_step": 0.01,
     "quote_currency": None, "base_currency": None,
     "is_crypto": False, "notes": "Deriv OTC pip=0.01"},
    {"symbol": "OTC_SPC", "asset_class": "synthetic",
     "pip_size": 0.01, "point_value": 0.01,
     "contract_size": 1.0,
     "lot_size_min": 0.01, "lot_size_max": 100.0,
     "lot_size_step": 0.01,
     "quote_currency": None, "base_currency": None,
     "is_crypto": False, "notes": "Deriv OTC pip=0.01"},
    # ---- CRYPTO (from Binance exchangeInfo) ----
    {"symbol": "AVAXUSDT", "asset_class": "crypto",
     "pip_size": 0.01, "point_value": 1.0,
     "contract_size": 1.0,
     "lot_size_min": 0.01, "lot_size_max": 90000000.0,
     "lot_size_step": 0.01,
     "quote_currency": "USDT", "base_currency": "AVAX",
     "is_crypto": True, "notes": "Binance exchangeInfo"},
    {"symbol": "BIOUSDT", "asset_class": "crypto",
     "pip_size": 0.0001, "point_value": 1.0,
     "contract_size": 1.0,
     "lot_size_min": 0.1, "lot_size_max": 9000000.0,
     "lot_size_step": 0.1,
     "quote_currency": "USDT", "base_currency": "BIO",
     "is_crypto": True, "notes": "Binance exchangeInfo"},
    {"symbol": "BTCUSDT", "asset_class": "crypto",
     "pip_size": 0.01, "point_value": 1.0,
     "contract_size": 1.0,
     "lot_size_min": 0.00001, "lot_size_max": 9000.0,
     "lot_size_step": 0.00001,
     "quote_currency": "USDT", "base_currency": "BTC",
     "is_crypto": True, "notes": "Binance exchangeInfo"},
    {"symbol": "DASHUSDT", "asset_class": "crypto",
     "pip_size": 0.01, "point_value": 1.0,
     "contract_size": 1.0,
     "lot_size_min": 0.001, "lot_size_max": 90000000.0,
     "lot_size_step": 0.001,
     "quote_currency": "USDT", "base_currency": "DASH",
     "is_crypto": True, "notes": "Binance exchangeInfo"},
    {"symbol": "DUSDT", "asset_class": "crypto",
     "pip_size": 0.00001, "point_value": 1.0,
     "contract_size": 1.0,
     "lot_size_min": 1.0, "lot_size_max": 9222449.0,
     "lot_size_step": 1.0,
     "quote_currency": "USDT", "base_currency": "D",
     "is_crypto": True, "notes": "Binance exchangeInfo"},
    {"symbol": "ENJUSDT", "asset_class": "crypto",
     "pip_size": 0.00001, "point_value": 1.0,
     "contract_size": 1.0,
     "lot_size_min": 0.1, "lot_size_max": 9000000.0,
     "lot_size_step": 0.1,
     "quote_currency": "USDT", "base_currency": "ENJ",
     "is_crypto": True, "notes": "Binance exchangeInfo"},
    {"symbol": "EURUSDT", "asset_class": "crypto",
     "pip_size": 0.0001, "point_value": 1.0,
     "contract_size": 1.0,
     "lot_size_min": 0.1, "lot_size_max": 9000000.0,
     "lot_size_step": 0.1,
     "quote_currency": "USDT", "base_currency": "EUR",
     "is_crypto": True, "notes": "Binance exchangeInfo"},
    {"symbol": "HEMIUSDT", "asset_class": "crypto",
     "pip_size": 0.00001, "point_value": 1.0,
     "contract_size": 1.0,
     "lot_size_min": 0.1, "lot_size_max": 9000000.0,
     "lot_size_step": 0.1,
     "quote_currency": "USDT", "base_currency": "HEMI",
     "is_crypto": True, "notes": "Binance exchangeInfo"},
    {"symbol": "NEARUSDT", "asset_class": "crypto",
     "pip_size": 0.001, "point_value": 1.0,
     "contract_size": 1.0,
     "lot_size_min": 0.1, "lot_size_max": 9000000.0,
     "lot_size_step": 0.1,
     "quote_currency": "USDT", "base_currency": "NEAR",
     "is_crypto": True, "notes": "Binance exchangeInfo"},
    {"symbol": "OGUSDT", "asset_class": "crypto",
     "pip_size": 0.001, "point_value": 1.0,
     "contract_size": 1.0,
     "lot_size_min": 0.1, "lot_size_max": 9000000.0,
     "lot_size_step": 0.1,
     "quote_currency": "USDT", "base_currency": "OG",
     "is_crypto": True, "notes": "Binance exchangeInfo"},
    {"symbol": "PAXGUSDT", "asset_class": "crypto",
     "pip_size": 0.01, "point_value": 1.0,
     "contract_size": 1.0,
     "lot_size_min": 0.0001, "lot_size_max": 9000000.0,
     "lot_size_step": 0.0001,
     "quote_currency": "USDT", "base_currency": "PAXG",
     "is_crypto": True, "notes": "Binance exchangeInfo"},
    {"symbol": "TAOUSDT", "asset_class": "crypto",
     "pip_size": 0.1, "point_value": 1.0,
     "contract_size": 1.0,
     "lot_size_min": 0.0001, "lot_size_max": 9000000.0,
     "lot_size_step": 0.0001,
     "quote_currency": "USDT", "base_currency": "TAO",
     "is_crypto": True, "notes": "Binance exchangeInfo"},
    {"symbol": "TONUSDT", "asset_class": "crypto",
     "pip_size": 0.001, "point_value": 1.0,
     "contract_size": 1.0,
     "lot_size_min": 0.01, "lot_size_max": 9000000.0,
     "lot_size_step": 0.01,
     "quote_currency": "USDT", "base_currency": "TON",
     "is_crypto": True, "notes": "Binance exchangeInfo"},
    {"symbol": "TRUMPUSDT", "asset_class": "crypto",
     "pip_size": 0.001, "point_value": 1.0,
     "contract_size": 1.0,
     "lot_size_min": 0.001, "lot_size_max": 9000000.0,
     "lot_size_step": 0.001,
     "quote_currency": "USDT", "base_currency": "TRUMP",
     "is_crypto": True, "notes": "Binance exchangeInfo"},
    {"symbol": "WLFIUSDT", "asset_class": "crypto",
     "pip_size": 0.0001, "point_value": 1.0,
     "contract_size": 1.0,
     "lot_size_min": 0.1, "lot_size_max": 9000000.0,
     "lot_size_step": 0.1,
     "quote_currency": "USDT", "base_currency": "WLFI",
     "is_crypto": True, "notes": "Binance exchangeInfo"},
    {"symbol": "XAUTUSDT", "asset_class": "crypto",
     "pip_size": 0.01, "point_value": 1.0,
     "contract_size": 1.0,
     "lot_size_min": 0.0001, "lot_size_max": 9000000.0,
     "lot_size_step": 0.0001,
     "quote_currency": "USDT", "base_currency": "XAUT",
     "is_crypto": True, "notes": "Binance exchangeInfo"},
    {"symbol": "ZAMAUSDT", "asset_class": "crypto",
     "pip_size": 0.00001, "point_value": 1.0,
     "contract_size": 1.0,
     "lot_size_min": 1.0, "lot_size_max": 9000000.0,
     "lot_size_step": 1.0,
     "quote_currency": "USDT", "base_currency": "ZAMA",
     "is_crypto": True, "notes": "Binance exchangeInfo"},
    # ---- INDICES (yfinance) ----
    {"symbol": "SPX500", "asset_class": "indices",
     "pip_size": 0.01, "point_value": 1.0,
     "contract_size": 1.0,
     "lot_size_min": 0.01, "lot_size_max": 100.0,
     "lot_size_step": 0.01,
     "quote_currency": "USD", "base_currency": "SPX",
     "is_crypto": False, "notes": "yfinance ^GSPC"},
    {"symbol": "NAS100", "asset_class": "indices",
     "pip_size": 0.01, "point_value": 1.0,
     "contract_size": 1.0,
     "lot_size_min": 0.01, "lot_size_max": 100.0,
     "lot_size_step": 0.01,
     "quote_currency": "USD", "base_currency": "NAS",
     "is_crypto": False, "notes": "yfinance ^NDX"},
    {"symbol": "CRYBTCUSD", "asset_class": "synthetic",
     "pip_size": 0.001, "point_value": 0.001,
     "contract_size": 1.0,
     "lot_size_min": 0.01, "lot_size_max": 100.0,
     "lot_size_step": 0.01,
     "quote_currency": None, "base_currency": None,
     "is_crypto": False,
     "notes": "Deriv synthetic BTC/USD. pip=0.001"},
    # ---- INDICES (yfinance, additional) ----
    {"symbol": "US30", "asset_class": "indices",
     "pip_size": 0.01, "point_value": 1.0,
     "contract_size": 1.0,
     "lot_size_min": 0.01, "lot_size_max": 100.0,
     "lot_size_step": 0.01,
     "quote_currency": "USD", "base_currency": "DJI",
     "is_crypto": False, "notes": "yfinance ^DJI"},
    {"symbol": "UK100", "asset_class": "indices",
     "pip_size": 0.01, "point_value": 1.0,
     "contract_size": 1.0,
     "lot_size_min": 0.01, "lot_size_max": 100.0,
     "lot_size_step": 0.01,
     "quote_currency": "GBP", "base_currency": "FTSE",
     "is_crypto": False, "notes": "yfinance ^FTSE"},
    {"symbol": "HK50", "asset_class": "indices",
     "pip_size": 0.01, "point_value": 1.0,
     "contract_size": 1.0,
     "lot_size_min": 0.01, "lot_size_max": 100.0,
     "lot_size_step": 0.01,
     "quote_currency": "HKD", "base_currency": "HSI",
     "is_crypto": False, "notes": "yfinance ^HSI"},
    # ---- FOREX EXOTICS (yfinance) ----
    {"symbol": "FRXUSDZAR", "asset_class": "forex",
     "pip_size": 0.00001, "point_value": 0.0,
     "contract_size": 100000.0,
     "lot_size_min": 0.01, "lot_size_max": 100.0,
     "lot_size_step": 0.01,
     "quote_currency": "ZAR", "base_currency": "USD",
     "is_crypto": False, "notes": "compute live"},
    {"symbol": "FRXEURTRY", "asset_class": "forex",
     "pip_size": 0.00001, "point_value": 0.0,
     "contract_size": 100000.0,
     "lot_size_min": 0.01, "lot_size_max": 100.0,
     "lot_size_step": 0.01,
     "quote_currency": "TRY", "base_currency": "EUR",
     "is_crypto": False, "notes": "compute live"},
    # ---- EQUITIES (yfinance) ----
    {"symbol": "AAPL", "asset_class": "equities",
     "pip_size": 0.01, "point_value": 1.0, "contract_size": 1.0,
     "lot_size_min": 1.0, "lot_size_max": 100000.0, "lot_size_step": 1.0,
     "quote_currency": "USD", "base_currency": "AAPL",
     "is_crypto": False, "notes": "yfinance equity"},
    {"symbol": "MSFT", "asset_class": "equities",
     "pip_size": 0.01, "point_value": 1.0, "contract_size": 1.0,
     "lot_size_min": 1.0, "lot_size_max": 100000.0, "lot_size_step": 1.0,
     "quote_currency": "USD", "base_currency": "MSFT",
     "is_crypto": False, "notes": "yfinance equity"},
    {"symbol": "GOOGL", "asset_class": "equities",
     "pip_size": 0.01, "point_value": 1.0, "contract_size": 1.0,
     "lot_size_min": 1.0, "lot_size_max": 100000.0, "lot_size_step": 1.0,
     "quote_currency": "USD", "base_currency": "GOOGL",
     "is_crypto": False, "notes": "yfinance equity"},
    {"symbol": "META", "asset_class": "equities",
     "pip_size": 0.01, "point_value": 1.0, "contract_size": 1.0,
     "lot_size_min": 1.0, "lot_size_max": 100000.0, "lot_size_step": 1.0,
     "quote_currency": "USD", "base_currency": "META",
     "is_crypto": False, "notes": "yfinance equity"},
    {"symbol": "NVDA", "asset_class": "equities",
     "pip_size": 0.01, "point_value": 1.0, "contract_size": 1.0,
     "lot_size_min": 1.0, "lot_size_max": 100000.0, "lot_size_step": 1.0,
     "quote_currency": "USD", "base_currency": "NVDA",
     "is_crypto": False, "notes": "yfinance equity"},
    {"symbol": "TSLA", "asset_class": "equities",
     "pip_size": 0.01, "point_value": 1.0, "contract_size": 1.0,
     "lot_size_min": 1.0, "lot_size_max": 100000.0, "lot_size_step": 1.0,
     "quote_currency": "USD", "base_currency": "TSLA",
     "is_crypto": False, "notes": "yfinance equity"},
    {"symbol": "AMZN", "asset_class": "equities",
     "pip_size": 0.01, "point_value": 1.0, "contract_size": 1.0,
     "lot_size_min": 1.0, "lot_size_max": 100000.0, "lot_size_step": 1.0,
     "quote_currency": "USD", "base_currency": "AMZN",
     "is_crypto": False, "notes": "yfinance equity"},
    {"symbol": "HD", "asset_class": "equities",
     "pip_size": 0.01, "point_value": 1.0, "contract_size": 1.0,
     "lot_size_min": 1.0, "lot_size_max": 100000.0, "lot_size_step": 1.0,
     "quote_currency": "USD", "base_currency": "HD",
     "is_crypto": False, "notes": "yfinance equity"},
    {"symbol": "JPM", "asset_class": "equities",
     "pip_size": 0.01, "point_value": 1.0, "contract_size": 1.0,
     "lot_size_min": 1.0, "lot_size_max": 100000.0, "lot_size_step": 1.0,
     "quote_currency": "USD", "base_currency": "JPM",
     "is_crypto": False, "notes": "yfinance equity"},
    {"symbol": "V", "asset_class": "equities",
     "pip_size": 0.01, "point_value": 1.0, "contract_size": 1.0,
     "lot_size_min": 1.0, "lot_size_max": 100000.0, "lot_size_step": 1.0,
     "quote_currency": "USD", "base_currency": "V",
     "is_crypto": False, "notes": "yfinance equity"},
    {"symbol": "MA", "asset_class": "equities",
     "pip_size": 0.01, "point_value": 1.0, "contract_size": 1.0,
     "lot_size_min": 1.0, "lot_size_max": 100000.0, "lot_size_step": 1.0,
     "quote_currency": "USD", "base_currency": "MA",
     "is_crypto": False, "notes": "yfinance equity"},
    {"symbol": "BAC", "asset_class": "equities",
     "pip_size": 0.01, "point_value": 1.0, "contract_size": 1.0,
     "lot_size_min": 1.0, "lot_size_max": 100000.0, "lot_size_step": 1.0,
     "quote_currency": "USD", "base_currency": "BAC",
     "is_crypto": False, "notes": "yfinance equity"},
    {"symbol": "JNJ", "asset_class": "equities",
     "pip_size": 0.01, "point_value": 1.0, "contract_size": 1.0,
     "lot_size_min": 1.0, "lot_size_max": 100000.0, "lot_size_step": 1.0,
     "quote_currency": "USD", "base_currency": "JNJ",
     "is_crypto": False, "notes": "yfinance equity"},
    {"symbol": "UNH", "asset_class": "equities",
     "pip_size": 0.01, "point_value": 1.0, "contract_size": 1.0,
     "lot_size_min": 1.0, "lot_size_max": 100000.0, "lot_size_step": 1.0,
     "quote_currency": "USD", "base_currency": "UNH",
     "is_crypto": False, "notes": "yfinance equity"},
    {"symbol": "PFE", "asset_class": "equities",
     "pip_size": 0.01, "point_value": 1.0, "contract_size": 1.0,
     "lot_size_min": 1.0, "lot_size_max": 100000.0, "lot_size_step": 1.0,
     "quote_currency": "USD", "base_currency": "PFE",
     "is_crypto": False, "notes": "yfinance equity"},
    {"symbol": "XOM", "asset_class": "equities",
     "pip_size": 0.01, "point_value": 1.0, "contract_size": 1.0,
     "lot_size_min": 1.0, "lot_size_max": 100000.0, "lot_size_step": 1.0,
     "quote_currency": "USD", "base_currency": "XOM",
     "is_crypto": False, "notes": "yfinance equity"},
    {"symbol": "CVX", "asset_class": "equities",
     "pip_size": 0.01, "point_value": 1.0, "contract_size": 1.0,
     "lot_size_min": 1.0, "lot_size_max": 100000.0, "lot_size_step": 1.0,
     "quote_currency": "USD", "base_currency": "CVX",
     "is_crypto": False, "notes": "yfinance equity"},
    {"symbol": "CAT", "asset_class": "equities",
     "pip_size": 0.01, "point_value": 1.0, "contract_size": 1.0,
     "lot_size_min": 1.0, "lot_size_max": 100000.0, "lot_size_step": 1.0,
     "quote_currency": "USD", "base_currency": "CAT",
     "is_crypto": False, "notes": "yfinance equity"},
    {"symbol": "NFLX", "asset_class": "equities",
     "pip_size": 0.01, "point_value": 1.0, "contract_size": 1.0,
     "lot_size_min": 1.0, "lot_size_max": 100000.0, "lot_size_step": 1.0,
     "quote_currency": "USD", "base_currency": "NFLX",
     "is_crypto": False, "notes": "yfinance equity"},
    {"symbol": "SBUX", "asset_class": "equities",
     "pip_size": 0.01, "point_value": 1.0, "contract_size": 1.0,
     "lot_size_min": 1.0, "lot_size_max": 100000.0, "lot_size_step": 1.0,
     "quote_currency": "USD", "base_currency": "SBUX",
     "is_crypto": False, "notes": "yfinance equity"},
]
